site_name: Uzi
theme:
  name: material
  custom_dir: docs/override
  features:
    - toc.follow
    - navigation.instant
    - navigation.tracking
    - navigation.top
    # - navigation.indexes
    # - navigation.expand
    # - navigation.sections


repo_name: pyuzi/uzi
repo_url: https://github.com/pyuzi/uzi
edit_uri: "blob/master/docs/"

use_directory_urls: false

nav:
  - 'Home': 'index.md'
  - 'why.md'
  # - 'features.md'
  - 'concepts.md'
  - 'install.md'
  - 'Basic User Guide': 
    - 'basic/index.md'
    - 'basic/providers/index.md'
  - 'Advanced User Guide': 
    - 'advanced/index.md'
  - 'Examples': 
    - 'examples/index.md'
  - 'Framework Integration': 
    - 'Overview': 'frameworks/index.md'
    - 'frameworks/django.md'
    - 'frameworks/sanic.md'
  - 'API Reference': 
    - 'uzi': 'api/index.md'
    - 'uzi.containers': 'api/containers.md'
    - 'uzi.exceptions': 'api/exceptions.md'
    - 'uzi.graph': 
      - 'api/graph/index.md'
      - 'api/graph/nodes.md'
    - 'uzi.injectors': 'api/injectors.md'
    - 'uzi.markers': 'api/markers.md'
    - 'uzi.providers':
      - 'api/providers/provider.md'
      - 'api/providers/alias.md'
      - 'api/providers/annotation.md'
      - 'api/providers/callable.md'
      - 'api/providers/dep.md'
      - 'api/providers/factory.md'
      - 'api/providers/lookup.md'
      - 'api/providers/partial.md'
      - 'api/providers/registry.md'
      - 'api/providers/resource.md'
      - 'api/providers/singleton.md'
      - 'api/providers/union.md'
      - 'api/providers/value.md'
    - 'uzi.scopes': 'api/scopes.md'
    - 'uzi._common': 'api/_common.md'
    - 'uzi._functools': 'api/_functools.md'
    
  - 'Contributing': 'contributing.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - attr_list
  - md_in_html
  - def_list
  - toc:
      permalink: True
  - pymdownx.snippets:
      base_path: .
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  analytics:
    provider: google
    property: G-TMB4GDY4Y7
  version:
    provider: mike

plugins:
  - mike:
      version_selector: true
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
            # docstring_options:
              # replace_admonitions: no 
          rendering:
            show_source: false
            show_root_heading: true
            members_order: source
            merge_init_into_class: false
            separate_signature: false
            show_signature_annotations: true
            docstring_section_style: table
      custom_templates: templates
      watch:
        - uzi