site_name: XDI
theme:
  name: material
  custom_dir: docs/override
  features:
    - toc.follow
    - navigation.instant
    - navigation.tracking
    - navigation.top

    # - navigation.indexes
    # - navigation.expand
    # - navigation.sections


repo_name: pyxdi/xdi
repo_url: https://github.com/pyxdi/xdi
edit_uri: "blob/master/docs/"


nav:
  - 'Home': 'index.md'
  - 'Introduction':
    - 'features.md'
    - 'concepts.md'
    - 'install.md'
  - 'Basic User Guide': 
    - 'basic/index.md'
    - 'basic/providers/index.md'
  - 'Advanced User Guide': 
    - 'advanced/index.md'
  - 'API Reference': 
    - 'xdi.core': 'api/core.md'
    - 'xdi.markers': 'api/markers.md'
    - 'xdi.containers': 'api/containers.md'
    - 'xdi.scopes': 'api/scopes.md'
    - 'xdi.injectors': 'api/injectors.md'
    - 'xdi.providers':
      - 'api/providers/base.md'
      - 'api/providers/alias.md'
      - 'api/providers/value.md'
      - 'api/providers/factory.md'
      - 'api/providers/singleton.md'
      - 'api/providers/resource.md'
      - 'api/providers/partial.md'
      - 'api/providers/callable.md'
      - 'api/providers/dep.md'
      - 'api/providers/lookup.md'
      - 'api/providers/union.md'
      - 'api/providers/annotation.md'
      - 'api/providers/registry.md'
  - 'Contributing': 'contributing.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - attr_list
  - md_in_html
  - def_list
  - toc:
      permalink: True
  - pymdownx.snippets:
      base_path: .
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  analytics:
    provider: google
    property: G-WS80L3FT2L
  version:
    provider: mike

plugins:
  - mike:
      version_selector: true
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
            # docstring_options:
              # replace_admonitions: no 
          rendering:
            show_source: false
            show_root_heading: true
            members_order: source
            merge_init_into_class: false
            separate_signature: false
            show_signature_annotations: true
            docstring_section_style: table
      custom_templates: templates
      watch:
        - xdi